# Global build settings.
[build]
  publish = "dist"
  command = "npm run production"

[build.environment]
  NODE_VERSION = "22"

## https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file

[[redirects]]
  from = "/blog/building-a-modern-drupal-theme-with-storybook"
  to = "/blog/migrating-your-drupal-theme-from-patternlab-to-storybook"
  status = 301

[[redirects]]
  from = "/blog/migrating-from-patternlab-to-storybook"
  to = "/blog/migrating-your-drupal-theme-from-patternlab-to-storybook"
  status = 301

[[redirects]]
  from = "/blog/responsive-images-in-drupal-a-guide"
  to = "/blog/responsive-images-in-drupal-a-series"
  status = 301

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

  [plugins.inputs]
    baseUrl = "https://mariohernandez.io"
    sitemapPath = "/sitemap.xml"
    ignorePeriod = 0
    providers = ["google", "yandex"]
